import { useCallback, useEffect, useState } from 'react';
import { Alert, Button, Card, Checkbox, Empty, Input, Modal, Popconfirm, Select, Space, Spin, Tag, Typography, message } from 'antd';
import { Link, history, request, useParams } from 'umi';
import { IoPreview, type IoSnapshot } from '@/components/canvas/CanvasIoPanel';
import { createClientUuid } from '@/utils/uuid';
export default function ProjectDetail() {
  const { id } = useParams<{ id: string }>(); const [project,setProject] = useState<any>(); const [loading,setLoading] = useState(true); const [busy,setBusy] = useState(false); const [mode,setMode] = useState<string>(); const [name,setName] = useState(''); const [note,setNote] = useState(''); const [all,setAll] = useState<any[]>([]); const [canvasId,setCanvasId] = useState<string>();
  const [choices,setChoices] = useState<any[]>([]); const [selected,setSelected] = useState<string[]>([]); const [viewId,setViewId] = useState<string>();
  const load = useCallback(async () => { try { const data = await request<any>(`/api/projects/${id}`); setProject(data); setViewId(data.activeResultId); } catch { message.error('读取项目失败'); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  const command = async (commandName: string, payload: any) => { setBusy(true); try { const result = await request<any>(`/api/projects/${id}/command`, { method: 'POST', data: { command: commandName, payload, expectedRevision: project.revision, idempotencyKey: createClientUuid(), actorId: 'human-project' }, timeout: 180000 }); await load(); return result; } catch (error: any) { message.error(error?.response?.data?.message || '操作失败'); throw error; } finally { setBusy(false); } };
  const startCollect = async () => {
    try {
      const ios = await Promise.all(project.canvases.map(async (canvas: any) => ({ canvas, io: await request<any>(`/api/canvas/${canvas.id}/io`) })));
      const options = ios.flatMap(({canvas,io}: any) => { const output = io.outputs.at(-1); return (output?.items ?? []).map((item: any) => ({ key: `${canvas.id}:${item.itemKey}`, canvasName: canvas.name, item, selection: { canvasId: canvas.id, itemKey: item.itemKey, outputsVersion: output.version, name: item.name, note: item.note } })); });
      setChoices(options); setSelected(options.map((c: any) => c.key)); setName('项目成果'); setNote(''); setMode('collect');
    } catch { message.error('读取画布输出失败'); }
  };
  const result: IoSnapshot | undefined = project?.results.find((s: IoSnapshot) => s.id === viewId);
  return <Spin spinning={loading}>{project && <div style={{ padding: 24 }}>
    <Link to="/projects">← 项目列表</Link><Space wrap style={{ width: '100%', justifyContent: 'space-between', marginTop: 12 }}><div><Typography.Title level={3} style={{ margin: 0 }}>{project.name}</Typography.Title><Typography.Paragraph type="secondary">{project.description}</Typography.Paragraph></div><Space><Button disabled={busy} onClick={() => { setName(project.name); setNote(project.description); setMode('edit'); }}>编辑项目</Button><Popconfirm title="删除项目及其成果副本？" description={project.canvases.length ? '项目仍包含画布，请先移出所有画布。' : '不会删除任何画布。'} disabled={!!project.canvases.length || busy} onConfirm={async () => { try { await request(`/api/projects/${id}`, { method: 'DELETE', data: { expectedRevision: project.revision } }); history.push('/projects'); } catch (error: any) { message.error(error?.response?.data?.message || '删除失败'); } }}><Button danger disabled={!!project.canvases.length || busy}>删除项目</Button></Popconfirm></Space></Space>
    <Space style={{ width: '100%', justifyContent: 'space-between', margin: '20px 0 12px' }}><Typography.Title level={4} style={{ margin: 0 }}>画布集合</Typography.Title><Space><Button disabled={busy} onClick={async () => { try { setAll((await request<any[]>('/api/canvas')).filter(c => !project.canvases.some((n: any) => n.id === c.id))); setCanvasId(undefined); setMode('add'); } catch { message.error('读取画布失败'); } }}>加入已有画布</Button><Button type="primary" disabled={busy} onClick={() => { setName(''); setMode('create'); }}>新建画布</Button></Space></Space>
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(260px,1fr))', gap: 12 }}>{project.canvases.map((canvas: any) => <Card key={canvas.id} title={<Link to={`/canvas/${canvas.id}`}>{canvas.name}</Link>} extra={<Popconfirm title="移出当前项目？" description="画布和其他项目的关联不受影响。" onConfirm={() => command('canvas.remove', { canvasId: canvas.id }).catch(() => {})}><Button size="small" disabled={busy}>移出</Button></Popconfirm>}><Tag>{canvas.nodeCount} 个节点</Tag><Tag>{(canvas.assetSize/1024/1024).toFixed(1)} MB</Tag></Card>)}</div>{!project.canvases.length && <Empty description="加入画布或创建一张新画布" />}
    <Space wrap style={{ width: '100%', justifyContent: 'space-between', margin: '28px 0 12px' }}><div><Typography.Title level={4} style={{ margin: 0 }}>项目产出</Typography.Title><Typography.Text type="secondary">最终成果的独立快照 · 仅用于浏览和下载</Typography.Text></div><Button type="primary" disabled={busy || !project.canvases.length} onClick={() => void startCollect()}>收集画布产出</Button></Space>
    {!!project.results.length && <Space wrap style={{ marginBottom: 12 }}><Select style={{ minWidth: 240 }} value={viewId} options={project.results.map((s: any) => ({ value: s.id, label: `v${s.version} · ${s.name || '项目成果'}${s.id === project.activeResultId ? ' · 当前' : ''}` }))} onChange={setViewId} />{viewId !== project.activeResultId && <Button disabled={busy} onClick={() => void command('results.restore', { snapshotId: viewId }).catch(() => {})}>设为当前成果</Button>}</Space>}
    {result ? <><Typography.Paragraph>{result.note}</Typography.Paragraph><Typography.Text type="secondary">保存于 {new Date(result.createdAt).toLocaleString()}</Typography.Text><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(280px,1fr))', gap: 16, marginTop: 12 }}>{result.items.map(item => <Card key={item.itemKey} title={item.name}><Typography.Paragraph type="secondary">来源：{item.sourceCanvasName}</Typography.Paragraph><IoPreview item={item} /></Card>)}</div>{!result.items.length && <Empty description="该版本没有成果" />}</> : <Empty description="从关联画布选择最终成果，保存为项目快照" />}
    <Modal title={mode === 'edit' ? '编辑项目' : mode === 'create' ? '新建画布' : '加入已有画布'} open={['edit','create','add'].includes(mode || '')} onCancel={() => setMode(undefined)} confirmLoading={busy} okButtonProps={{ disabled: mode === 'add' && !canvasId }} onOk={async () => { try { const response = await command(mode === 'edit' ? 'edit' : mode === 'create' ? 'canvas.create' : 'canvas.add', mode === 'add' ? { canvasId } : mode === 'edit' ? { name, description: note } : { name }); setMode(undefined); if (response.createdCanvasId) history.push(`/canvas/${response.createdCanvasId}`); } catch { /* shown */ } }}>
      {mode === 'add' ? <Select style={{ width: '100%' }} showSearch optionFilterProp="label" value={canvasId} onChange={setCanvasId} placeholder="选择画布（可同时加入多个项目）" options={all.map(c => ({ value: c.id, label: c.name }))} /> : <><Input value={name} onChange={e => setName(e.target.value)} placeholder="名称" maxLength={200} />{mode === 'edit' && <Input.TextArea value={note} onChange={e => setNote(e.target.value)} maxLength={2000} style={{ marginTop: 12 }} />}</>}
    </Modal>
    <Modal title="保存项目成果快照" open={mode === 'collect'} width={720} onCancel={() => setMode(undefined)} confirmLoading={busy} okButtonProps={{ disabled: !selected.length }} onOk={() => command('results.capture', { name, note, selections: selected.map(key => choices.find(c => c.key === key).selection) }).then(() => setMode(undefined)).catch(() => {})}>
      <Alert type="info" message="复制所选内容，保存后不随画布变化；再次收集会产生新版本。" /><Input value={name} onChange={e => setName(e.target.value)} placeholder="成果版本名称" maxLength={200} style={{ marginTop: 12 }} /><Input.TextArea value={note} onChange={e => setNote(e.target.value)} placeholder="交付说明" maxLength={2000} style={{ marginTop: 8 }} />
      {!choices.length && <Empty description="关联画布尚未发布输出" />}
      {choices.map((choice,index) => <Card key={choice.key} size="small" style={{ marginTop: 12 }} title={<Checkbox checked={selected.includes(choice.key)} onChange={e => setSelected(keys => e.target.checked ? [...keys,choice.key] : keys.filter(k => k !== choice.key))}>{choice.canvasName} · {choice.item.name}</Checkbox>} extra={index > 0 && <Button size="small" onClick={() => setChoices(values => { const next = [...values]; [next[index-1],next[index]] = [next[index],next[index-1]]; setSelected(keys => next.filter(c => keys.includes(c.key)).map(c => c.key)); return next; })}>上移</Button>}><IoPreview item={choice.item} /><Input defaultValue={choice.selection.name} maxLength={200} placeholder="成果名称" onChange={e => setChoices(values => values.map(c => c.key === choice.key ? { ...c, selection: { ...c.selection, name: e.target.value } } : c))} /><Input.TextArea defaultValue={choice.selection.note} maxLength={2000} placeholder="成果说明" onChange={e => setChoices(values => values.map(c => c.key === choice.key ? { ...c, selection: { ...c.selection, note: e.target.value } } : c))} style={{ marginTop: 8 }} /></Card>)}
    </Modal>
  </div>}</Spin>;
}
