import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash,randomUUID} from 'node:crypto';
const base='http://localhost:3100/api';const fixture=JSON.parse(await readFile(new URL('fixture.json',import.meta.url)));
const api=async(path,method='GET',body)=>{const r=await fetch(base+path,{method,...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});assert(r.ok,`${method} ${path}: ${r.status}`);return r.status===204?null:r.json()};
const digest=async id=>{const r=await fetch(`${base}/assets/${id}/download`);assert(r.ok);return createHash('sha256').update(Buffer.from(await r.arrayBuffer())).digest('hex')};
const read=async()=>{const ios=await Promise.all(fixture.canvases.map(id=>api(`/canvas/${id}/io`)));const project=await api(`/projects/${fixture.projects[0]}`);const ids=new Set([...ios.flatMap(io=>[...io.inputs.flatMap(g=>g.snapshots),...io.outputs].flatMap(s=>s.items.map(i=>i.assetId))),...project.results.flatMap(s=>s.items.map(i=>i.assetId))]);return{ios,project,hashes:Object.fromEntries(await Promise.all([...ids].map(async id=>[id,await digest(id)])))}};
if(process.argv[2]==='before'){await writeFile(new URL('persistence-before.json',import.meta.url),JSON.stringify(await read(),null,2));console.log('Saved IO/project manifests and file hashes before restart.');}
else{const before=JSON.parse(await readFile(new URL('persistence-before.json',import.meta.url)));assert.deepEqual(await read(),before);const target=await api(`/canvas/${fixture.target}`);const source=await api(`/canvas/${fixture.source}`);const lease=await api(`/canvas/${fixture.source}/control/acquire`,'POST',{holderType:'agent',holderId:`delete-fixture-${fixture.source}`});await api(`/canvas/${fixture.source}`,'DELETE',{leaseToken:lease.leaseToken,leaseEpoch:lease.epoch,expectedRevision:source.revision,idempotencyKey:randomUUID(),actorType:'agent',actorId:lease.holderId});assert.deepEqual(await api(`/canvas/${fixture.target}`),target);const preview=await api(`/canvas/${fixture.target}/io/inputs/${fixture.groupId}/update-preview`);assert.equal(preview.available,false);const p=await api(`/projects/${fixture.projects[0]}`);assert.deepEqual(p.results,before.project.results);for(const item of [...target.io.inputs.flatMap(g=>g.snapshots).flatMap(s=>s.items),...p.results.flatMap(s=>s.items)])assert.equal(await digest(item.assetId),before.hashes[item.assetId]);await writeFile(new URL('acceptance-report.json',import.meta.url),JSON.stringify({date:new Date().toISOString(),checks:[...fixture.checks,'human-output-publish','human-project-results-capture','restart-manifest-and-file-hashes','source-delete-keeps-target-and-project-results'],backend:{suites:22,tests:185},frontendBuild:'passed'},null,2));console.log('Restart persistence and source deletion independence passed.');}
